---
name: "Release on push"

on:
  push:
    branches:
      - main
    paths:
      - "script/**"
      - "Dockerfile"
      - "entrypoint.sh"

jobs:
  images-build:
    uses: bjw-s/pmb/.github/workflows/action-image-build.yaml@main
    needs:
      - get-version
    with:
      pushImages: "true"
      version: "rolling"
    secrets: inherit
